### ISSUE TITLE
List Builder - currently used in Spectrum Management Console 

### ISSUE THREAD

**Issue by fondo213** [PBGUX/designsystem#105]
The Spectrum Management Console has a list builder - see screenshots. I would like to use the same thing in the Spatial Manager application. Developers suggest that maybe it become a DS control so both apps inherit it from there.
<img width="829" alt="screen shot 2016-04-08 at 1 27 33 pm" src="https://cloud.githubusercontent.com/assets/10961179/14392197/265825b6-fd8e-11e5-85ad-44470f251961.png">
<img width="866" alt="screen shot 2016-04-08 at 1 29 49 pm" src="https://cloud.githubusercontent.com/assets/10961179/14392201/2d247552-fd8e-11e5-8b46-e525b1b9eb68.png">

**Comment by smlombardi** [comment]
Can't these items be made from the [existing table examples](http://guxstaging.pbi.global.pvt/design_system/#/tables/datatable#data-tables)? We have tabs, checkbox rows, and toolbar buttons.

**Comment by fondo213** [comment]
Sure, I suppose they could.
I guess this gets philosophical at this point.
Is the design system pieces and parts? Or is it controls that help a user accomplish a task (e.g. Build a list)? Or is it page types?
If y'all want to stop at pieces and parts that's fine, but we'll get more variation in implementation. Some variation is warranted and desirable of course, but variation because folks put pieces and parts together differently is not desirable variation.
I'll leave it up to the DS folks to sort out the philosophical questions.
If it's my backlog I'd call this a lower priority since there is a "workaround" - assuming I believe the request is a valid one - that the "feature" is desirable.
D


Dave Fondacaro


Advisory User Experience Designer (IxD)

Global User Experience


T  518.285.7134

M 518.852.1551


dave.fondacaro@pb.com<mailto:dave.fondacaro@pb.com>

pitneybowes.com<file://composeviewinternalloadurl/www.pitneybowes.com>


Pitney Bowes

1 Global View

Troy, NY 12180

**Comment by lombardi-gux** [comment]
Follow the "view it on github" link for context

view it on GitHub<https://github.com/PBGUX/designsystem/issues/105#issuecomment-207563432>


On Apr 8, 2016, at 3:09 PM, fondo213 <notifications@github.com<mailto:notifications@github.com>> wrote:

Sure, I suppose they could.
I guess this gets philosophical at this point.
Is the design system pieces and parts? Or is it controls that help a user accomplish a task (e.g. Build a list)? Or is it page types?
If y'all want to stop at pieces and parts that's fine, but we'll get more variation in implementation. Some variation is warranted and desirable of course, but variation because folks put pieces and parts together differently is not desirable variation.
I'll leave it up to the DS folks to sort out the philosophical questions.
If it's my backlog I'd call this a lower priority since there is a "workaround" - assuming I believe the request is a valid one - that the "feature" is desirable.
D


Dave Fondacaro


Advisory User Experience Designer (IxD)

Global User Experience


T 518.285.7134

M 518.852.1551


dave.fondacaro@pb.com<mailto:dave.fondacaro@pb.com><mailto:dave.fondacaro@pb.com>

pitneybowes.com<http://pitneybowes.com><file://composeviewinternalloadurl/www.pitneybowes.com>


Pitney Bowes

1 Global View

Troy, NY 12180

**Comment by danielcollettepb** [comment]
@fondo213 the DS is `pieces and parts` that you put together, like legos. We do have this pattern captured as @smlombardi points out. Each product will have different requirements as to what parts are used, what we have is a basic example.
