### ISSUE TITLE
Application Settings title text wraps in the dropdown menu

### ISSUE THREAD

**Issue by jrnorrisjr** [PBGUX/designsystem#142]
![settingsmenu](https://cloud.githubusercontent.com/assets/8123985/16522579/bc5b8b3c-3f6c-11e6-91c7-375144982d43.png)

The application settings title wraps if the menu items are short.

**Comment by lombardi-gux** [comment]
Thanks. We will be re-examining menus. For now, perhaps reduce font size 1px or decrease right padding in that menu.

--




On Fri, Jul 1, 2016 at 9:21 AM -0400, "jrnorrisjr" <notifications@github.com<mailto:notifications@github.com>> wrote:


[settingsmenu]<https://cloud.githubusercontent.com/assets/8123985/16522579/bc5b8b3c-3f6c-11e6-91c7-375144982d43.png>

The application settings title wraps if the menu items are short.

-
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub<https://github.com/PBGUX/designsystem/issues/142>, or mute the thread<https://github.com/notifications/unsubscribe/AHHUkkiBIXpySuEVYVeQXdu1GePMHcw4ks5qRRRIgaJpZM4JDI14>.

________________________________

**Comment by danielcollettepb** [comment]
You can also apply the class `text-nowrap` to the Application Settings element:

http://getbootstrap.com/css/#type-alignment
