### ISSUE TITLE
toggle buttons

### ISSUE THREAD

**Issue by shawnss** [PBGUX/designsystem#16]
With the latest css toggle buttons are now gray. Is this by design or something got missed. In action they don't look right beside other toolbar buttons:

![toggle](https://cloud.githubusercontent.com/assets/7524790/7052177/f730c9d6-ddfa-11e4-802c-c69f61109874.png)
![toolbar](https://cloud.githubusercontent.com/assets/7524790/7052181/fb3cf1ee-ddfa-11e4-8855-c21e2e413a9d.png)

**Comment by lombardi-gux** [comment]
Under review, will revise shortly. Thanks.

On Apr 8, 2015, at 2:26 PM, shawnss <notifications@github.com<mailto:notifications@github.com>> wrote:


With the latest css toggle buttons are now gray. Is this by design or something got missed. In action they don't look right beside other toolbar buttons:

[toggle]<https://cloud.githubusercontent.com/assets/7524790/7052177/f730c9d6-ddfa-11e4-802c-c69f61109874.png>
[toolbar]<https://cloud.githubusercontent.com/assets/7524790/7052181/fb3cf1ee-ddfa-11e4-8855-c21e2e413a9d.png>

—
Reply to this email directly or view it on GitHub<https://github.com/PBGUX/designsystem/issues/16>.


________________________________

**Comment by danielcollettepb** [comment]
can you email me a fullpage screenshot of these buttons as used in the application?

**Comment by shawnss** [comment]
Here it is. The these two buttons are used to show either a tabular list of records or single record in a form view.
![editor](https://cloud.githubusercontent.com/assets/7524790/7074148/3a819640-dec6-11e4-9d2b-ee552125586b.PNG)

**Comment by shawnss** [comment]
Also here it is with the new css:
![editor](https://cloud.githubusercontent.com/assets/7524790/7075215/2624898e-dece-11e4-881a-19c6bcda4892.PNG)

**Comment by shawnss** [comment]
Did you guys get to review this issue? Have not heard anything back.
Thanks.

**Comment by danielcollettepb** [comment]
Yes we did review, Victor had an action item I believe... let me check on where this stands. Sorry about that...

**Comment by shawnss** [comment]
No big deal. Just wanted to check that it'll be done at some point. Thanks.

**Comment by shawnss** [comment]
Hi guys. We only have 2 weeks of development before code freeze. Is this going to change soon?
Thanks

**Comment by danielcollettepb** [comment]
You can use a `btn-group` with single buttons to get a consistent look across the top of the table, see this plunker:

http://plnkr.co/edit/bq1BtJbfLTRKeVyhehIP?p=preview

The guidance is that the controls above the table should be visually pushed back (by making them gray) so that the content stands out.

![image](https://cloud.githubusercontent.com/assets/6116867/8094200/7eb8554e-0f93-11e5-992f-ae983f484b1e.png)
