### ISSUE TITLE
Use Angular-UI Buttons

### ISSUE THREAD

**Issue by dustin2524** [PBGUX/designsystem#34]
We use the [buttons supplied by Angular UI](https://angular-ui.github.io/bootstrap/#/buttons) (as I imagine anyone using the design system is). They are much more compatible with angular than the bootstrap 3 button component. 

This makes it slightly difficult to use certain design system styles. For example, the '[Simple Toggle](http://guxstaging.pbi.global.pvt/design_system/#/buttons)' button cant be directly used because you have styling for `data-toggle="buttons"` , which angular ui buttons dont use.

It would also be easier to reuse (copy/paste) your buttons if they were already following the Angular UI markup. 

This same issue applies to `dropdown` and `accordion` components.

**Comment by lombardi-gux** [comment]
Typical simple buttons, such as  we use generic html5 "button" elements.  We supply styling classes for those buttons and all the bootstrap buttons.

None of out styles are dependent on Bootstrap's (or any other) Javascript.  You can nook up whatever you want to to them/

From: dustin2524
Reply-To: PBGUX/designsystem
Date: Friday, October 16, 2015 at 2:13 PM
To: PBGUX/designsystem
Subject: [designsystem] Use Angular-UI Buttons (#34)


We use the buttons supplied by Angular UI<https://angular-ui.github.io/bootstrap/#/buttons> (as I imagine anyone using the design system is). They are much more compatible with angular than the bootstrap 3 button component.

This makes it slightly difficult to use certain design system styles. For example, the 'Simple Toggle<http://guxstaging.pbi.global.pvt/design_system/#/buttons>' button cant be directly used because you have styling for data-toggle="buttons" , which angular ui buttons dont use.

It would also be easier to reuse (copy/paste) your buttons if they were already following the Angular UI markup.

This same issue applies to dropdown and accordion components.

—
Reply to this email directly or view it on GitHub<https://github.com/PBGUX/designsystem/issues/34>.

________________________________

**Comment by dustin2524** [comment]
I believe the issue is because the design system buttons and dropdowns use `data-toggle="dropdown"` , `data-toggle="buttons"`, etc. These bootstraps js components are styled by bootstrap and certain things are styled around them. For example,

Currently in the live preview (using `data-toggle="buttons"`) :
![image](https://cloud.githubusercontent.com/assets/4664726/10549987/4048186a-7412-11e5-9624-345378f02bbc.png)

In our app, where we dont use `data-toggle="buttons"` because we dont use bootstrap js components:
![image](https://cloud.githubusercontent.com/assets/4664726/10550028/6e5b355c-7412-11e5-8524-290ba48f1481.png)

**Comment by danielcollettepb** [comment]
good point @dustin2524... I'm adding this to our buglist to create an example in the DS site and to fix any styling issues. Will keep you posted.

**Comment by danielcollettepb** [comment]
I dropped an example of radio buttons straight from the ui-bootstrap site ([link](https://angular-ui.github.io/bootstrap/#/buttons)) into our page and the buttons are styled correctly. We are using the latest v0.14.2. What version are you using and can you send a snippet of the html markup?

![image](https://cloud.githubusercontent.com/assets/6116867/10610995/2ed4593c-7718-11e5-8f15-5fecad14b010.png)


```html
<div class="btn-group">
  <label class="btn btn-primary" ng-model="radioModel" uib-btn-radio="'Left'">Left</label>
  <label class="btn btn-primary" ng-model="radioModel" uib-btn-radio="'Middle'">Middle</label>
  <label class="btn btn-primary" ng-model="radioModel" uib-btn-radio="'Right'">Right</label>
</div>
```

**Comment by dustin2524** [comment]
Sorry, I see I was accidentally using a hybrid of boostrap's component along with UI-bootstraps component. I had an input inside the labels which appears to not be needed. Removing these inputs gave the appropriate styling. Thank you.

**Comment by danielcollettepb** [comment]
Great to hear this worked out. Thanks for contributing @dustin2524!
