### ISSUE TITLE
Numeric-Stepper defunct?

### ISSUE THREAD

**Issue by rdukeshier** [PBGUX/designsystem#84]
The [steppers](http://guxstaging.pbi.global.pvt/design_system/#/uicontrols#steppers) section of the design system suggests using [Numeric-Stepper](https://github.com/xFlatlinex/Numeric-Stepper).  It doesn't appear that this library is being maintained (no updates in 4+ years).  Should we be investigating an alternative?

**Comment by smlombardi** [comment]
We can use this one: http://choroshin.github.io/angular-ui-numeric/

Thoughts?

**Comment by danielcollettepb** [comment]
@smlombardi please add a JIRA task referencing this issue and assign to @irshad-ak

**Comment by shawnss** [comment]
is there a reason not to use [kendo core](https://github.com/telerik/kendo-ui-core) for some of these controls? It's open source, free, and would not be abandoned any time soon. Angular is part of the core and they already have Angular 2 support. 

Disclaimer: we are using the professional version in Spectrum BSM.

**Comment by smlombardi** [comment]
We had looked at it at one point but rejected it at the time for 4 reasons:

1. cost
2.  the need to have the whole (rather large) library when you just wanted a few controls
3. at the time, anyway, it's angular support was weak
4. we did not want to be tied to their update cycle

Not sure if all of those conditions are still true.

**Comment by shawnss** [comment]
Maybe it's worth looking at it again. It's now free (except data visualization that comes with paid professional version). They have done a good job with Angular (they support the latest Angular with their releases and they already have Angular 2) and you can pick and choose components you want if smaller js is desired. I got tired of other components getting abandoned before I was even finished with my development and since we were already using it in BSM, decided to use other components such as date, dropdowns, etc. No problem and was easy to override their styles to match the DS styles (built-in support for bootstrap). Just a suggestion as it may not be the right choice for everyone.

**Comment by danielcollettepb** [comment]
For 3.0 we changed the stepper to use angular-touchspin:

https://github.com/nkovacic/angular-touchspin

I added a story to explore Kendo UI post 3.0, will recommend to have this prioritized
